MESSAGES = {
    "FAQ_UPLOADED" : "FAQ uploaded successfully.",
    "FAQ_REQUIRED": "FAQ data is required.",
    "FAQ_UPLOADED_FAILED" : "FAQ upload failed.",
    "FAQ_RETRIEVED" : "FAQ retrieved successfully.",
    "FAQ_NOT_FOUND" : "FAQ not found.",
    "FAQ_UPDATED" : "FAQ updated successfully.",
    "FAQ_DELETED" : "FAQ deleted successfully.",
    "FAQ_NOT_FOUND" : "FAQ not found.",
    "FAQ_COUNT" : "FAQ count retrieved successfully.",
    "FAQ_DELETE_FAILED" : "FAQ delete failed.",
    "FAQ_UPDATE_FAILED" : "FAQ update failed.",
    "FAQ_COUNT_FAILED" : "FAQ count failed.",
    "UNEXPECTED_ERROR" : "An unexpected error occurred.",
    "FIELDS_MISSING": "Missing required fields.",
    "REQUIRED_FIELDS": "All required fields are missing.",
    "STRIPE_ERROR" : "An error occurred while processing your payment. Please try again later.",
    "PRODUCT_RETRIVED" : "Product retrieved successfully.",
    "PRODUCT_NOT_FOUND" : "Product not found.",
    "PRODUCT_ID_MISSING" : "Product ID is missing.",
    "SESSION_GENERATED" : "Session generated successfully.",
    "PRICE_FIELD_NOT_FOUND" : "Price field not found.",
    "PRICE_NOT_FOUND" : "Price not found.",
    "CUSTOMER_FOUND" : "Customer found.",
    "CUSTOMER_NOT_FOUND" : "Customer noy found.",
    "SUBSCRIPTION_PRICE_UPDATED" : "Subscription Price Update",
    "SUBSCRIPTIONS_FOUND": "Subscriptions found.",
    "STRIPE_ERROR": "An error occurred while processing your payment. Please try again later.",
    "SOMETHING_WENT_WRONG": "Something went wrong.",
    "SUBSCRIPTION_ID_REQUIRED": "Subscription ID is required.",
    "SUBSCRIPTION_NOT_FOUND": "Subscription not found.",
    
}