# Generated by Django 4.2.17 on 2025-03-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]