# Generated by Django 4.2.17 on 2025-03-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_users_business_name_users_context_users_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='context',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='link_for_website',
            new_name='website_link',
        ),
    ]
