# Generated by Django 4.2.17 on 2025-03-17 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_context_users_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='product',
        ),
        migrations.RemoveField(
            model_name='users',
            name='website_link',
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
