# Generated by Django 4.2.17 on 2025-03-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_users_business_name_remove_users_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
