# Generated by Django 4.2.17 on 2025-03-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_useraccount_code_users_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='code',
        ),
    ]
