# Generated by Django 4.2.17 on 2025-03-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_useraccount_code_users_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.TextField()),
                ('snippet', models.TextField()),
                ('history_id', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('recipients', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
