# Generated by Django 4.2.17 on 2025-03-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_useraccount_history_id_users_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    
    ]
