# Generated by Django 4.2.17 on 2025-03-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_email_account_users_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='account',
            new_name='account_id',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='account_id',
        ),
    ]
