# Generated by Django 4.2.17 on 2025-03-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_rename_account_email_account_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='account_id',
            new_name='account',
        ),
    ]
