# Generated by Django 4.2.17 on 2025-03-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_rename_account_id_email_account_users_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='account',
        ),
    ]
