# Generated by Django 4.2.17 on 2025-03-20 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_email_account_users_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='authentication.useraccount'),
        ),
    ]
