# Generated by Django 4.2.17 on 2025-03-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_users_is_deleted_sentemail'),
    ]
    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_logged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        )

    ]
