# Generated by Django 4.2.17 on 2025-03-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_useraccount_is_logged_useraccount_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('manual_review', 'Manual Review'), ('processed', 'Processed')], default='sent', max_length=20),
        )
    ]
