# Generated by Django 4.2.17 on 2025-03-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_email_status_users_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='status',
        ),
        migrations.AddField(
            model_name='email',
            name='is_incident',
            field=models.BooleanField(default=False),
        ),
    ]
