# Generated by Django 4.2.17 on 2025-04-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_remove_email_status_email_is_incident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
