# Generated by Django 4.2.17 on 2025-04-01 10:05
 
from django.db import migrations
 
 
class Migration(migrations.Migration):
 
    dependencies = [
        ('authentication', '0002_users_is_deleted'),
        ('authentication', '0019_users_is_deleted'),
    ]
 
    operations = [
    ]