# Generated by Django 4.2.17 on 2025-04-07 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_merge_0002_users_is_deleted_0019_users_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='related_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='authentication.email'),
        ),
    ]
