# Generated by Django 4.2.17 on 2025-04-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='trial_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
