# Generated by Django 4.2.17 on 2025-04-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_users_trial_active_users_trial_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='trial_active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='trial_start_date',
        ),
        migrations.AddField(
            model_name='users',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
