# Generated by Django 4.2.17 on 2025-04-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_remove_users_trial_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='reply_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI')], default='ai', max_length=10),
        ),
    ]
