# Generated by Django 4.2.17 on 2025-04-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_sentemail_reply_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
