# Generated by Django 4.2.17 on 2025-05-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_users_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='trial_email_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='trial_email_limit',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
