# Generated by Django 4.2.17 on 2025-05-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_users_trial_email_count_users_trial_email_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='imap_port',
            field=models.IntegerField(default=993),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='imap_server',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('IMAP', 'IMAP')], max_length=10),
        ),
    ]
