# Generated by Django 4.2.17 on 2025-05-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_useraccount_imap_port_useraccount_imap_server_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='imap_port',
            field=models.IntegerField(blank=True, default=993, null=True),
        ),
    ]
