# Generated by Django 4.2.17 on 2025-05-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_alter_useraccount_imap_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='imap_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
