# Generated by Django 4.2.17 on 2025-05-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_alter_useraccount_imap_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='access_token',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
