# Generated by Django 4.2.17 on 2025-05-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_alter_useraccount_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
