# Generated by Django 4.2.17 on 2025-06-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_alter_useraccount_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='subscription_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
