# Generated by Django 4.2.17 on 2025-03-03 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiintegration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airesponselog',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.email'),
        ),
    ]
