# Generated by Django 4.2.17 on 2025-03-07 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0003_airesponselog_is_deleted_apiintegration_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
